# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discount.proto',
  package='discount',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64iscount.proto\x12\x08\x64iscount\"\'\n\x12GetDiscountRequest\x12\x11\n\tproductID\x18\x01 \x01(\x05\")\n\x13GetDiscountResponse\x12\x12\n\npercentage\x18\x01 \x01(\x02\x32X\n\x08\x44iscount\x12L\n\x0bGetDiscount\x12\x1c.discount.GetDiscountRequest\x1a\x1d.discount.GetDiscountResponse\"\x00\x62\x06proto3'
)




_GETDISCOUNTREQUEST = _descriptor.Descriptor(
  name='GetDiscountRequest',
  full_name='discount.GetDiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='productID', full_name='discount.GetDiscountRequest.productID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=67,
)


_GETDISCOUNTRESPONSE = _descriptor.Descriptor(
  name='GetDiscountResponse',
  full_name='discount.GetDiscountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='discount.GetDiscountResponse.percentage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['GetDiscountRequest'] = _GETDISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['GetDiscountResponse'] = _GETDISCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDiscountRequest = _reflection.GeneratedProtocolMessageType('GetDiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDISCOUNTREQUEST,
  '__module__' : 'discount_pb2'
  # @@protoc_insertion_point(class_scope:discount.GetDiscountRequest)
  })
_sym_db.RegisterMessage(GetDiscountRequest)

GetDiscountResponse = _reflection.GeneratedProtocolMessageType('GetDiscountResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDISCOUNTRESPONSE,
  '__module__' : 'discount_pb2'
  # @@protoc_insertion_point(class_scope:discount.GetDiscountResponse)
  })
_sym_db.RegisterMessage(GetDiscountResponse)



_DISCOUNT = _descriptor.ServiceDescriptor(
  name='Discount',
  full_name='discount.Discount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=112,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDiscount',
    full_name='discount.Discount.GetDiscount',
    index=0,
    containing_service=None,
    input_type=_GETDISCOUNTREQUEST,
    output_type=_GETDISCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNT)

DESCRIPTOR.services_by_name['Discount'] = _DISCOUNT

# @@protoc_insertion_point(module_scope)
